= Reactor Reboot
:description: A programming puzzle that aims on writing clean code even for complex issues.
:url-repo: https://github.com/ISchwarz23/interview-puzzles

== Introduction/Explanation
include::../explanation.adoc[]

== Things you should consider
include::../things-to-consider.adoc[]

== Problem description
You are visiting your grandma in her nursing home. To fulfill some cliché, today is https://en.wikipedia.org/wiki/Bingo_(American_version)[bingo] day in the nursing home.

Bingo is played on a set of boards each consisting of a 5x5 grid of numbers. Numbers are chosen at random, and the chosen number is *marked* on all boards on which it appears. (Numbers may not appear on all boards.) If all numbers in any row or any column of a board are marked, that board *wins*. (Diagonals don't count.)

In your puzzle input you can find the drawn numbers in the first row and below a set of 5x5 boards. For example:

[source,txt,subs=+macros] 
----
7,4,9,5,11,17,23,2,0,14,21,24,10,16,13,6,15,25,12,22,18,20,8,19,3,26,1

22 13 17 11  0
 8  2 23  4 24
21  9 14 16  7
 6 10  3 18  5
 1 12 20 15 19

 3 15  0  2 22
 9 18 13 17  5
19  8  7 25 23
20 11 10 24  4
14 21 16 12  6

14 21 17 24  4
10 16 15  9 19
18  8 23 26 20
22 11 13  6  5
 2  0 12  3  7
----

After the first five numbers are drawn (`7`, `4`, `9`, `5`, and `11`), there are no winners, but the boards are marked as follows (shown here adjacent to each other to save space):

[source,txt,subs=+macros] 
----
22 13 17 pass:quotes[<mark>11</mark>]  0         3 15  0  2 22        14 21 17 24  4
 8  2 23 pass:quotes[<mark> 4</mark>] 24        pass:quotes[<mark> 9</mark>] 18 13 17 pass:quotes[<mark> 5</mark>]        10 16 15 pass:quotes[<mark> 9</mark>] 19
21 pass:quotes[<mark> 9</mark>] 14 16  pass:quotes[<mark>7</mark>]        19  8 pass:quotes[<mark> 7</mark>] 25 23        18  8 23 26 20
 6 10  3 18 pass:quotes[<mark> 5</mark>]        20 pass:quotes[<mark>11</mark>] 10 24 pass:quotes[<mark> 4</mark>]        22 pass:quotes[<mark>11</mark>] 13  6 pass:quotes[<mark> 5</mark>]
 1 12 20 15 19        14 21 16 12  6         2  0 12  3 pass:quotes[<mark> 7</mark>]
----

After the next six numbers are drawn (`17`, `23`, `2`, `0`, `14`, and `21`), there are still no winners:

[source,txt,subs=+macros] 
----
22 13 pass:quotes[<mark>17</mark>] pass:quotes[<mark>11</mark>] pass:quotes[<mark> 0</mark>]         3 15 pass:quotes[<mark> 0</mark>] pass:quotes[<mark> 2</mark>] 22        pass:quotes[<mark>14</mark>] pass:quotes[<mark>21</mark>] pass:quotes[<mark>17</mark>] 24 pass:quotes[<mark> 4</mark>]
 8 pass:quotes[<mark> 2</mark>] pass:quotes[<mark>23</mark>] pass:quotes[<mark> 4</mark>] 24        pass:quotes[<mark> 9</mark>] 18 13 pass:quotes[<mark>17</mark>] pass:quotes[<mark> 5</mark>]        10 16 15 pass:quotes[<mark> 9</mark>] 19
pass:quotes[<mark>21</mark>] pass:quotes[<mark> 9</mark>] pass:quotes[<mark>14</mark>] 16 pass:quotes[<mark> 7</mark>]        19  8 pass:quotes[<mark> 7</mark>] 25 pass:quotes[<mark>23</mark>]        18  8 pass:quotes[<mark>23</mark>] 26 20
 6 10  3 18 pass:quotes[<mark> 5</mark>]        20 pass:quotes[<mark>11</mark>] 10 24 pass:quotes[<mark> 4</mark>]        22 pass:quotes[<mark>11</mark>] 13  6 pass:quotes[<mark> 5</mark>]
 1 12 20 15 19        pass:quotes[<mark>14</mark>] pass:quotes[<mark>21</mark>] 16 12  6        pass:quotes[<mark> 2</mark>] pass:quotes[<mark> 0</mark>] 12  3 pass:quotes[<mark> 7</mark>]
----

Finally, `24` is drawn:

[source,txt,subs=+macros] 
----
22 13 pass:quotes[<mark>17</mark>] pass:quotes[<mark>11</mark>] pass:quotes[<mark> 0</mark>]         3 15 pass:quotes[<mark> 0</mark>] pass:quotes[<mark> 2</mark>] 22        pass:quotes[<mark>14</mark>] pass:quotes[<mark>21</mark>] pass:quotes[<mark>17</mark>] pass:quotes[<mark>24</mark>] pass:quotes[<mark> 4</mark>]
 8 pass:quotes[<mark> 2</mark>] pass:quotes[<mark>23</mark>] pass:quotes[<mark> 4</mark>] pass:quotes[<mark>24</mark>]        pass:quotes[<mark> 9</mark>] 18 13 pass:quotes[<mark>17</mark>] pass:quotes[<mark> 5</mark>]        10 16 15 pass:quotes[<mark> 9</mark>] 19
pass:quotes[<mark>21</mark>] pass:quotes[<mark> 9</mark>] pass:quotes[<mark>14</mark>] 16 pass:quotes[<mark> 7</mark>]        19  8 pass:quotes[<mark> 7</mark>] 25 pass:quotes[<mark>23</mark>]        18  8 pass:quotes[<mark>23</mark>] 26 20
 6 10  3 18 pass:quotes[<mark> 5</mark>]        20 pass:quotes[<mark>11</mark>] 10 pass:quotes[<mark>24</mark>] pass:quotes[<mark> 4</mark>]        22 pass:quotes[<mark>11</mark>] 13  6 pass:quotes[<mark> 5</mark>]
 1 12 20 15 19        pass:quotes[<mark>14</mark>] pass:quotes[<mark>21</mark>] 16 12  6        pass:quotes[<mark> 2</mark>] pass:quotes[<mark> 0</mark>] 12  3 pass:quotes[<mark> 7</mark>]
----

At this point, the third board *wins* because it has at least one complete row or column of marked numbers (in this case, the entire top row is marked: `14 21 17 24 4`).

The *score* of the winning board can now be calculated. Start by finding the *sum of all unmarked numbers* on that board; in this case, the sum is `188`. Then, *multiply that sum by the number that was just called* when the board won, `24`, to get the final score, `188 * 24 = 4512`.

== Assignment 1
To guarantee victory against your grandma, figure out which board will win first. *What will your final score be if you choose that board?*

== Assignment 2
On the other hand, it might be wise to try a different strategy: let your grandma win.

You aren't sure how many bingo boards an old lady can play at once, so the safe thing to do is to *figure out which board will win last* and choose that one. That way, no matter which boards she picks, she will win for sure.

In the above example, the second board is the last to win, which happens after `13` is eventually called and its middle column is completely marked. If you were to keep playing until this point, the second board would have a sum of unmarked numbers equal to `148` for a final score of `148 * 13 = 1924`.

Figure out which board will win last. *Once it wins, what would its final score be?*
