= Sea Cucumber
:description: A programming puzzle that aims on writing clean code.
:url-repo: https://github.com/ISchwarz23/interview-puzzles

== Introduction/Explanation
include::../explanation.adoc[]

== Things you should consider
include::../things-to-consider.adoc[]

== Problem description
You are inside a submarine looking for your keys, that fell into the ocean.

This is it: the bottom of the ocean trench, the last place the sleigh keys could be. Your submarine's experimental antenna *still isn't boosted enough* to detect the keys, but they must be here. All you need to do is *reach the seafloor* and find them.

At least, you'd touch down on the seafloor if you could; unfortunately, it's completely covered by two large herds of https://en.wikipedia.org/wiki/Sea_cucumber[sea cucumbers], and there isn't an open space large enough for your submarine.

There are two herds of sea cucumbers sharing the same region; one always moves east (`>`), while the other always moves south (`v`). Each location can contain at most one sea cucumber; the remaining locations are empty (`.`). The submarine helpfully generates a map of the situation (input-example.txt). For example:

 v...>>.vv>
 .vv>>.vv..
 >>.>v>...v
 >>v>>.>.v.
 v>v.vv.v..
 >.>>..v...
 .vv..>.>v.
 v.v..>>v.v
 ....v..v.>

Every *step*, the sea cucumbers in the east-facing herd attempt to move forward one location, then the sea cucumbers in the south-facing herd attempt to move forward one location. When a herd moves forward, every sea cucumber in the herd first simultaneously considers whether there is a sea cucumber in the adjacent location it's facing (even another sea cucumber facing the same direction), and then every sea cucumber facing an empty location simultaneously moves into that location.

So, in a situation like this:

 ...>>>>>...

After one step, only the rightmost sea cucumber would have moved:

 ...>>>>.>..

After the next step, two sea cucumbers move:

 ...>>>.>.>.

During a single step, the east-facing herd moves first, then the south-facing herd moves. So, given this situation:

 ..........
 .>v....v..
 .......>..
 ..........

After a single step, of the sea cucumbers on the left, only the south-facing sea cucumber has moved (as it wasn't out of the way in time for the east-facing cucumber on the left to move), but both sea cucumbers on the right have moved (as the east-facing sea cucumber moved out of the way of the south-facing sea cucumber):

 ..........
 .>........
 ..v....v>.
 ..........

Due to *strong water currents* in the area, sea cucumbers that move off the right edge of the map appear on the left edge, and sea cucumbers that move off the bottom edge of the map appear on the top edge. Sea cucumbers always check whether their destination location is empty before moving, even if that destination is on the opposite side of the map:

Initial state:

 ...>...
 .......
 ......>
 v.....>
 ......>
 .......
 ..vvv..

After 1 step:

 ..vv>..
 .......
 >......
 v.....>
 >......
 .......
 ....v..

After 2 steps:

 ....v>.
 ..vv...
 .>.....
 ......>
 v>.....
 .......
 .......

After 3 steps:

 ......>
 ..v.v..
 ..>v...
 >......
 ..>....
 v......
 .......

After 4 steps:

 >......
 ..v....
 ..>.v..
 .>.v...
 ...>...
 .......
 v......

To find a safe place to land your submarine, the sea cucumbers need to stop moving. Again consider the first example (input-example.txt):

Initial state:

 v...>>.vv>
 .vv>>.vv..
 >>.>v>...v
 >>v>>.>.v.
 v>v.vv.v..
 >.>>..v...
 .vv..>.>v.
 v.v..>>v.v
 ....v..v.>

After 1 step:

 ....>.>v.>
 v.v>.>v.v.
 >v>>..>v..
 >>v>v>.>.v
 .>v.v...v.
 v>>.>vvv..
 ..v...>>..
 vv...>>vv.
 >.v.v..v.v

After 2 steps:

 >.v.v>>..v
 v.v.>>vv..
 >v>.>.>.v.
 >>v>v.>v>.
 .>..v....v
 .>v>>.v.v.
 v....v>v>.
 .vv..>>v..
 v>.....vv.

After 3 steps:

 v>v.v>.>v.
 v...>>.v.v
 >vv>.>v>..
 >>v>v.>.v>
 ..>....v..
 .>.>v>v..v
 ..v..v>vv>
 v.v..>>v..
 .v>....v..

After 4 steps:

 v>..v.>>..
 v.v.>.>.v.
 >vv.>>.v>v
 >>.>..v>.>
 ..v>v...v.
 ..>>.>vv..
 >.v.vv>v.v
 .....>>vv.
 vvv>...v..

After 5 steps:

 vv>...>v>.
 v.v.v>.>v.
 >.v.>.>.>v
 >v>.>..v>>
 ..v>v.v...
 ..>.>>vvv.
 .>...v>v..
 ..v.v>>v.v
 v.v.>...v.

...

After 10 steps:

 ..>..>>vv.
 v.....>>.v
 ..v.v>>>v>
 v>.>v.>>>.
 ..v>v.vv.v
 .v.>>>.v..
 v.v..>v>..
 ..v...>v.>
 .vv..v>vv.

...

After 20 steps:

 v>.....>>.
 >vv>.....v
 .>v>v.vv>>
 v>>>v.>v.>
 ....vv>v..
 .v.>>>vvv.
 ..v..>>vv.
 v.v...>>.v
 ..v.....v>

...

After 30 steps:

 .vv.v..>>>
 v>...v...>
 >.v>.>vv.>
 >v>.>.>v.>
 .>..v.vv..
 ..v>..>>v.
 ....v>..>v
 v.v...>vv>
 v.v...>vvv

...

After 40 steps:

 >>v>v..v..
 ..>>v..vv.
 ..>>>v.>.v
 ..>>>>vvv>
 v.....>...
 v.v...>v>>
 >vv.....v>
 .>v...v.>v
 vvv.v..v.>

...

After 50 steps:

 ..>>v>vv.v
 ..v.>>vv..
 v.>>v>>v..
 ..>>>>>vv.
 vvv....>vv
 ..v....>>>
 v>.......>
 .vv>....v>
 .>v.vv.v..

...

After 55 steps:

 ..>>v>vv..
 ..v.>>vv..
 ..>>v>>vv.
 ..>>>>>vv.
 v......>vv
 v>v....>>v
 vvv...>..>
 >vv.....>.
 .>v.vv.v..

After 56 steps:

 ..>>v>vv..
 ..v.>>vv..
 ..>>v>>vv.
 ..>>>>>vv.
 v......>vv
 v>v....>>v
 vvv....>.>
 >vv......>
 .>v.vv.v..

After 57 steps:

 ..>>v>vv..
 ..v.>>vv..
 ..>>v>>vv.
 ..>>>>>vv.
 v......>vv
 v>v....>>v
 vvv.....>>
 >vv......>
 .>v.vv.v..

After 58 steps:

 ..>>v>vv..
 ..v.>>vv..
 ..>>v>>vv.
 ..>>>>>vv.
 v......>vv
 v>v....>>v
 vvv.....>>
 >vv......>
 .>v.vv.v..

In this example (input-example.txt), the sea cucumbers stop moving after 58 steps.


== Assignment 1

Find somewhere safe to land your submarine. *What is the first step on which no sea cucumbers move? (using map in input.txt)*


== Assignment 2

Your submarine tells you, that you made a mistake. The movement order is different as you thought. In fact, the south-moving sea cucumber herd moves first and the east-moving herd moves second. All the other rules still apply. *What is now the first step on which no sea cucumber move? (using map from input.txt)*