name: Build asciidoctor document
on: [push]
jobs:
  build_asciidoctor:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile asciidoctor document
        uses: lmoesle/asciidoc-action@latest
      - name: Upload 'packet-decoder'
        uses: actions/upload-artifact@v3
        with:
          name: packet-decoder
          path: |
            packet-decoder/
            !**/*.adoc
