name: Generate Puzzles
on: [push]
jobs:
  build_asciidoctor:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile puzzles to PDF
        uses: lmoesle/asciidoc-action@latest
      - name: Upload 'packet-decoder'
        uses: actions/upload-artifact@v3
        with:
          name: packet-decoder
          path: |
            packet-decoder/
            !**/*.adoc
      - name: Upload 'passage-pathing'
        uses: actions/upload-artifact@v3
        with:
          name: passage-pathing
          path: |
            passage-pathing/
            !**/*.adoc
      - name: Upload 'sea-cucumber'
        uses: actions/upload-artifact@v3
        with:
          name: sea-cucumber
          path: |
            sea-cucumber/
            !**/*.adoc
