name: Generate Puzzles
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - puzzle_name: bingo
          - puzzle_name: chiton
    steps:
      - name: Set up git repository
        uses: actions/checkout@v2
      - name: Compile puzzles to PDF
        uses: lmoesle/asciidoc-action@latest
      - name: Create '${{matrix.puzzle_name}}' zip
        run: zip -D -r ${{matrix.puzzle_name}}.zip ${{matrix.puzzle_name}}/ -x "*.adoc"
      - name: Upload '${{matrix.puzzle_name}}' to release
        uses: svenstaro/upload-release-action@v2
        with:
          overwrite: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{matrix.puzzle_name}}.zip
          asset_name: ${{matrix.puzzle_name}}
          tag: latest
